// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	analysis "github.com/MattWindsor91/act-tester/internal/plan/analysis"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnAnalysis provides a mock function with given fields: a
func (_m *Observer) OnAnalysis(a analysis.Analysis) {
	_m.Called(a)
}
