// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	compiler "github.com/c4-project/c4t/internal/model/service/compiler"

	mock "github.com/stretchr/testify/mock"

	service "github.com/c4-project/c4t/internal/model/service"
)

// Driver is an autogenerated mock type for the Driver type
type Driver struct {
	mock.Mock
}

// RunCompiler provides a mock function with given fields: ctx, j, sr
func (_m *Driver) RunCompiler(ctx context.Context, j compiler.Job, sr service.Runner) error {
	ret := _m.Called(ctx, j, sr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, compiler.Job, service.Runner) error); ok {
		r0 = rf(ctx, j, sr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
