// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/c4-project/c4t/internal/model/service/compiler"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Driver is an autogenerated mock type for the Driver type
type Driver struct {
	mock.Mock
}

// RunCompiler provides a mock function with given fields: ctx, j, errw
func (_m *Driver) RunCompiler(ctx context.Context, j compiler.Job, errw io.Writer) error {
	ret := _m.Called(ctx, j, errw)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, compiler.Job, io.Writer) error); ok {
		r0 = rf(ctx, j, errw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
