// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/MattWindsor91/act-tester/internal/model/service"
	mock "github.com/stretchr/testify/mock"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, r
func (_m *Runner) Run(ctx context.Context, r service.RunInfo) error {
	ret := _m.Called(ctx, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.RunInfo) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
