// Package runner contains the logic for the single-file test runner.
package runner

import (
	"context"

	"github.com/MattWindsor91/act-tester/internal/pkg/plan"

	"github.com/MattWindsor91/act-tester/internal/pkg/model"
)

// Compiler is the interface of things that can run compilers.
type Compiler interface {
	// Run runs the compiler pointed to by compiler on the input files infiles, outputting a binary to outfile.
	Compile(compiler model.ID, infiles string, outfile string) error
}

// Runner contains the configuration required to perform a single test run.
type Runner struct {
	// Plan is the machine plan on which this runner is operating.
	Plan plan.MachinePlan

	// Compiler is the compiler runner that we're using to do this test run.
	Compiler Compiler

	// OutDir contains the root output directory for things generated by this runner.
	OutDir string
}

// Run runs the runner on p.
// Run is not thread-safe.
func (r *Runner) Run(ctx context.Context, p *plan.Plan) (*plan.Plan, error) {
	return nil, nil
}
