.nh
.TH act\-tester 8

.SH NAME
.PP
act\-tester \- runs compiler tests


.SH SYNOPSIS
.PP
act\-tester

.PP
.RS

.nf
[\-\-cpuprofile]=[value]
[\-\-machine\-filter|\-m]=[value]
[\-\-no\-dashboard|\-D]
[\-A]=[value]
[\-C]=[value]
[\-k]=[value]
[\-n]=[value]
[\-x]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
act\-tester [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-cpuprofile\fP="": \fB\fCfile\fR into which we should dump pprof information

.PP
\fB\-\-machine\-filter, \-m\fP="": a \fB\fCglob\fR to use to filter incoming machines by ID

.PP
\fB\-\-no\-dashboard, \-D\fP: turns off the dashboard

.PP
\fB\-A\fP="": read ACT config from this \fB\fCfile\fR

.PP
\fB\-C\fP="": read tester config from this \fB\fCfile\fR

.PP
\fB\-k\fP="": number of \fB\fCcycles\fR to run for each subject in the corpus (default: 10)

.PP
\fB\-n\fP="": \fB\fCnumber\fR of corpus files to select for this test plan;
if non\-positive, the planner will use all viable provided corpus files (default: 0)

.PP
\fB\-x\fP: if true, use 'dune exec' to run OCaml ACT binaries
