// Code generated by "stringer -type Stage"; DO NOT EDIT.

package stage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Plan-1]
	_ = x[Fuzz-2]
	_ = x[Lift-3]
	_ = x[Invoke-4]
	_ = x[Compile-5]
	_ = x[Run-6]
	_ = x[Analyse-7]
}

const _Stage_name = "UnknownPlanFuzzLiftInvokeCompileRunAnalyse"

var _Stage_index = [...]uint8{0, 7, 11, 15, 19, 25, 32, 35, 42}

func (i Stage) String() string {
	if i >= Stage(len(_Stage_index)-1) {
		return "Stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stage_name[_Stage_index[i]:_Stage_index[i+1]]
}
