// Code generated by "stringer -type Stage"; DO NOT EDIT.

package stage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Plan-1]
	_ = x[Perturb-2]
	_ = x[Fuzz-3]
	_ = x[Lift-4]
	_ = x[Invoke-5]
	_ = x[Compile-6]
	_ = x[Run-7]
	_ = x[Analyse-8]
}

const _Stage_name = "UnknownPlanPerturbFuzzLiftInvokeCompileRunAnalyse"

var _Stage_index = [...]uint8{0, 7, 11, 18, 22, 26, 32, 39, 42, 49}

func (i Stage) String() string {
	if i >= Stage(len(_Stage_index)-1) {
		return "Stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stage_name[_Stage_index[i]:_Stage_index[i+1]]
}
