// Package lifter contains the part of the tester framework that lifts litmus tests to compilable C.
// It does so by means of a backend HarnessMaker.
package lifter

import (
	"context"

	"github.com/MattWindsor91/act-tester/internal/pkg/model"
	"github.com/sirupsen/logrus"
)

// HarnessMaker is an interface capturing the ability to make test harnesses.
type HarnessMaker interface {
	// MakeHarness asks the harness maker to make the test harness described by spec.
	// It returns a list outfiles of files created (C files, header files, etc.), and/or an error err.
	MakeHarness(spec model.HarnessSpec) (outFiles []string, err error)
}

// Lifter holds the main configuration for the lifter part of the tester framework.
type Lifter struct {
	// Plan is the plan on which this lifter is operating.
	Plan model.Plan

	// Maker is a harness maker.
	Maker HarnessMaker

	// OutDir contains the root output directory for things generated by this fuzzer.
	OutDir string
}

// LiftPlanFile loads a plan from file, runs the lifter on it, then outputs the plan to stdout.
func (l *Lifter) LiftPlanFile(ctx context.Context, file string) error {
	logrus.Infoln("loading plan from", file)
	if err := l.Plan.Load(file); err != nil {
		return err
	}
	if err := l.Lift(ctx); err != nil {
		return err
	}
	return l.Plan.Dump()
}

// Lift runs a lifting job: taking every test subject in a plan and using a backend to lift each into a test harness.
func (l *Lifter) Lift(ctx context.Context) error {
	return l.Plan.ParMachines(ctx, l.liftMachine)
}

func (l *Lifter) count() int {
	i := 0
	for _, m := range l.Plan.Machines {
		i += len(m.Arches())
	}
	return i
}

func (l *Lifter) liftMachine(ctx context.Context, m model.MachinePlan) error {
	return nil
}
