.nh
.TH act\-tester\-invoke 8

.SH NAME
.PP
act\-tester\-invoke \- runs the machine\-dependent phase of an ACT test, potentially remotely


.SH SYNOPSIS
.PP
act\-tester\-invoke

.PP
.RS

.nf
[\-\-compiler\-timeout|\-t]=[value]
[\-\-num\-compiler\-workers|\-j]=[value]
[\-\-num\-run\-workers|\-J]=[value]
[\-\-run\-timeout|\-T]=[value]
[\-\-skip\-compiler]
[\-\-skip\-runner]
[\-C]=[value]
[\-d]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
act\-tester\-invoke [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-compiler\-timeout, \-t\fP="": a \fB\fCtimeout\fR to apply to each compilation (default: 1m0s)

.PP
\fB\-\-num\-compiler\-workers, \-j\fP="": number of compiler \fB\fCworkers\fR to run in parallel (default: 1)

.PP
\fB\-\-num\-run\-workers, \-J\fP="": number of runner \fB\fCworkers\fR to run in parallel (not recommended except on manycore machines) (default: 1)

.PP
\fB\-\-run\-timeout, \-T\fP="": a \fB\fCtimeout\fR to apply to each run (default: 1m0s)

.PP
\fB\-\-skip\-compiler\fP: if given, skip the compiler

.PP
\fB\-\-skip\-runner\fP: if given, skip the runner

.PP
\fB\-C\fP="": read tester config from this \fB\fCfile\fR

.PP
\fB\-d\fP="": \fB\fCdirectory\fR to which outputs will be written (default: mach\_results)
