// Code generated by "stringer -type Target"; DO NOT EDIT.

package backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ToDefault-0]
	_ = x[ToStandalone-1]
	_ = x[ToObjRecipe-2]
	_ = x[ToExeRecipe-3]
}

const _Target_name = "ToDefaultToStandaloneToObjRecipeToExeRecipe"

var _Target_index = [...]uint8{0, 9, 21, 32, 43}

func (i Target) String() string {
	if i >= Target(len(_Target_index)-1) {
		return "Target(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Target_name[_Target_index[i]:_Target_index[i+1]]
}
