.nh
.TH c4t\-fuzz 8

.SH NAME
.PP
c4t\-fuzz \- runs the batch\-fuzzer phase of a C4 test


.SH SYNOPSIS
.PP
c4t\-fuzz

.PP
.RS

.nf
[\-\-corpus\-size|\-n]=[value]
[\-\-verbose|\-v]
[\-C]=[value]
[\-d]=[value]
[\-k]=[value]
[\-x]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
c4t\-fuzz [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-corpus\-size, \-n\fP="": \fB\fCnumber\fR of corpus files to select for this test plan (default: 0)

.PP
\fB\-\-verbose, \-v\fP: enables verbose output

.PP
\fB\-C\fP="": read tester config from this \fB\fCfile\fR

.PP
\fB\-d\fP="": \fB\fCdirectory\fR to which outputs will be written (default: fuzz\_results)

.PP
\fB\-k\fP="": number of \fB\fCtimes\fR to fuzz each subject in the corpus (default: 10)

.PP
\fB\-x\fP: if true, use 'dune exec' to run c4f binaries
