.nh
.TH c4t\-obs 8

.SH NAME
.PP
c4t\-obs \- interpret observation files


.SH SYNOPSIS
.PP
c4t\-obs

.PP
.RS

.nf
[\-\-show\-interesting|\-i]
[\-\-show\-postcondition|\-p]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
c4t\-obs [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-show\-interesting, \-i\fP: print a summary of any 'interesting' states observed

.PP
\fB\-\-show\-postcondition, \-p\fP: print a Litmus (forall, sum of products) postcondition capturing the states observed
