.nh
.TH act\-litmus 8

.SH NAME
.PP
act\-litmus \- wraps litmus with various issue workarounds


.SH SYNOPSIS
.PP
act\-litmus

.PP
.RS

.nf
[\-\-c11]=[value]
[\-\-carch]=[value]
[\-A]=[value]
[\-o]=[value]
[\-v]
[\-x]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
act\-litmus [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-c11\fP="": for Litmus compatibility; ignored

.PP
\fB\-\-carch\fP="": C architecture to pass through to litmus

.PP
\fB\-A\fP="": read ACT config from this \fB\fCfile\fR

.PP
\fB\-o\fP="": output directory for harness

.PP
\fB\-v\fP: be more verbose

.PP
\fB\-x\fP: if true, use 'dune exec' to run OCaml ACT binaries
