// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	litmus "github.com/MattWindsor91/c4t/internal/model/litmus"
	mock "github.com/stretchr/testify/mock"
)

// StatDumper is an autogenerated mock type for the StatDumper type
type StatDumper struct {
	mock.Mock
}

// DumpStats provides a mock function with given fields: ctx, s, path
func (_m *StatDumper) DumpStats(ctx context.Context, s *litmus.Statset, path string) error {
	ret := _m.Called(ctx, s, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *litmus.Statset, string) error); ok {
		r0 = rf(ctx, s, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
