// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	id "github.com/MattWindsor91/act-tester/internal/model/id"

	mock "github.com/stretchr/testify/mock"
)

// Pather is an autogenerated mock type for the Pather type
type Pather struct {
	mock.Mock
}

// Path provides a mock function with given fields: arch, subject
func (_m *Pather) Path(arch id.ID, subject string) (string, error) {
	ret := _m.Called(arch, subject)

	var r0 string
	if rf, ok := ret.Get(0).(func(id.ID, string) string); ok {
		r0 = rf(arch, subject)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(id.ID, string) error); ok {
		r1 = rf(arch, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Prepare provides a mock function with given fields: arches, subjects
func (_m *Pather) Prepare(arches []id.ID, subjects []string) error {
	ret := _m.Called(arches, subjects)

	var r0 error
	if rf, ok := ret.Get(0).(func([]id.ID, []string) error); ok {
		r0 = rf(arches, subjects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
