// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	job "github.com/MattWindsor91/act-tester/internal/model/job"

	mock "github.com/stretchr/testify/mock"

	recipe "github.com/MattWindsor91/act-tester/internal/model/recipe"
)

// SingleLifter is an autogenerated mock type for the SingleLifter type
type SingleLifter struct {
	mock.Mock
}

// Lift provides a mock function with given fields: ctx, j, errw
func (_m *SingleLifter) Lift(ctx context.Context, j job.Lifter, errw io.Writer) (recipe.Recipe, error) {
	ret := _m.Called(ctx, j, errw)

	var r0 recipe.Recipe
	if rf, ok := ret.Get(0).(func(context.Context, job.Lifter, io.Writer) recipe.Recipe); ok {
		r0 = rf(ctx, j, errw)
	} else {
		r0 = ret.Get(0).(recipe.Recipe)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, job.Lifter, io.Writer) error); ok {
		r1 = rf(ctx, j, errw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
