// Code generated by "stringer -type Op"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[PushInputs-1]
	_ = x[PushInput-2]
	_ = x[CompileObj-3]
	_ = x[CompileExe-4]
	_ = x[RunExe-5]
	_ = x[Cat-6]
}

const _Op_name = "NopPushInputsPushInputCompileObjCompileExeRunExeCat"

var _Op_index = [...]uint8{0, 3, 13, 22, 32, 42, 48, 51}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
