// Code generated by "stringer -type Output"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutNothing-0]
	_ = x[OutObj-1]
	_ = x[OutExe-2]
}

const _Output_name = "OutNothingOutObjOutExe"

var _Output_index = [...]uint8{0, 10, 16, 22}

func (i Output) String() string {
	if i >= Output(len(_Output_index)-1) {
		return "Output(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Output_name[_Output_index[i]:_Output_index[i+1]]
}
