// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	act "github.com/MattWindsor91/act-tester/internal/act"

	mock "github.com/stretchr/testify/mock"
)

// CmdRunner is an autogenerated mock type for the CmdRunner type
type CmdRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, s
func (_m *CmdRunner) Run(ctx context.Context, s act.CmdSpec) error {
	ret := _m.Called(ctx, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, act.CmdSpec) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
