// Package director contains a test-plan fuzzer.
// It relies on the existence of a single-file fuzzer such as act-fuzz.
package fuzzer

import (
	"github.com/MattWindsor91/act-tester/internal/pkg/model"
	"github.com/sirupsen/logrus"
)

// SingleFuzzer represents types that can commune with a C litmus test fuzzer.
type SingleFuzzer interface {
	// FuzzSingle fuzzes the test at path inPath using the given seed, outputting to path outPath.
	FuzzSingle(seed int, inPath, outPath string) error
}

// Fuzzer holds the configuration required to fuzz a plan file.
type Fuzzer struct {
	model.PlanLoader

	// Driver holds the single-file fuzzer that the fuzzer is going to use.
	Driver SingleFuzzer

	// OutDir contains the root output directory for things generated by this fuzzer.
	OutDir string
}

// Fuzz runs the fuzzer.
func (f *Fuzzer) Fuzz() error {
	logrus.Infoln("loading plan")
	err := f.LoadPlan()

	// TODO(@MattWindsor91)
	return err
}
