// Copyright (c) 2020 Matt Windsor and contributors
//
// This file is part of act-tester.
// Licenced under the MIT licence; see `LICENSE`.

package subject

// CompileResult is a record about an attempt to compile a subject.
type CompileResult struct {
	// Success is true if the compilation succeeded.
	Success bool `toml:"success"`

	// Files contains paths to the files generated by the compilation.
	Files CompileFileset `toml:"files"`
}

// CompileFileset is the set of file paths associated with a compiler output.
type CompileFileset struct {
	// Bin is the path to this subject's compiled binary file.
	Bin string `toml:"bin,omitempty"`
	// Log is the path to this subject's compiler stderr log file.
	Log string `toml:"log,omitempty"`
}
