.nh
.TH act\-tester\-fuzz 8

.SH NAME
.PP
act\-tester\-fuzz \- runs the batch\-fuzzer phase of an ACT test


.SH SYNOPSIS
.PP
act\-tester\-fuzz

.PP
.RS

.nf
[\-A]=[value]
[\-C]=[value]
[\-d]=[value]
[\-k]=[value]
[\-n]=[value]
[\-x]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
act\-tester\-fuzz [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-A\fP="": read ACT config from this \fB\fCfile\fR

.PP
\fB\-C\fP="": read tester config from this \fB\fCfile\fR

.PP
\fB\-d\fP="": \fB\fCdirectory\fR to which outputs will be written (default: fuzz\_results)

.PP
\fB\-k\fP="": number of \fB\fCcycles\fR to run for each subject in the corpus (default: 10)

.PP
\fB\-n\fP="": \fB\fCnumber\fR of corpus files to select for this test plan;
if non\-positive, the planner will use all viable provided corpus files (default: 0)

.PP
\fB\-x\fP: if true, use 'dune exec' to run OCaml ACT binaries
