// Code generated by "stringer -type Tag -linecomment"; DO NOT EDIT.

package obs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TagUnknown-0]
	_ = x[TagWitness-1]
	_ = x[TagCounter-2]
}

const _Tag_name = "unknownwitnesscounter"

var _Tag_index = [...]uint8{0, 7, 14, 21}

func (i Tag) String() string {
	if i < 0 || i >= Tag(len(_Tag_index)-1) {
		return "Tag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tag_name[_Tag_index[i]:_Tag_index[i+1]]
}
