// Copyright (c) 2020 Matt Windsor and contributors
//
// This file is part of act-tester.
// Licenced under the MIT licence; see `LICENSE`.

package act_test

import (
	"fmt"
	"os"

	"github.com/MattWindsor91/act-tester/internal/act"
	"github.com/MattWindsor91/act-tester/internal/machine"
	"github.com/MattWindsor91/act-tester/internal/model/job"
)

// ExampleWriteFuzzConf is a testable example for WriteFuzzConf.
func ExampleWriteFuzzConf() {
	noMachine := job.Fuzzer{}
	if err := act.WriteFuzzConf(os.Stdout, noMachine); err != nil {
		fmt.Println("ERROR:", err)
	}

	fmt.Println("")

	mach := job.Fuzzer{Machine: &machine.Machine{Cores: 4}}
	if err := act.WriteFuzzConf(os.Stdout, mach); err != nil {
		fmt.Println("ERROR:", err)
	}

	// Output:
	// # AUTOGENERATED BY TESTER
	// fuzz {
	// }
	//
	// # AUTOGENERATED BY TESTER
	// fuzz {
	// ## MACHINE SPECIFIC OVERRIDES ##
	//   # Set to number of cores in machine to prevent thrashing.
	//   set param cap.threads to 4
	// }
}
