// Copyright (c) 2020 Matt Windsor and contributors
//
// This file is part of act-tester.
// Licenced under the MIT licence; see `LICENSE`.

package act

import (
	"fmt"
	"io"
	"io/ioutil"
	"text/template"

	"github.com/MattWindsor91/act-tester/internal/helper/errhelp"

	"github.com/MattWindsor91/act-tester/internal/model/job"
)

const fuzzConfTemplate = `# AUTOGENERATED BY TESTER
fuzz {
{{ if .Machine }}## MACHINE SPECIFIC OVERRIDES ##
  # Set to number of cores in machine to prevent thrashing.
  set param cap.threads to {{ .Machine.Cores }}
{{ end -}}
}
`

// WriteFuzzConf writes a fuzzer configuration based on j to w.
func WriteFuzzConf(w io.Writer, j job.Fuzzer) error {
	t, err := template.New("fuzzConf").Parse(fuzzConfTemplate)
	if err != nil {
		return err
	}
	return t.Execute(w, j)
}

// MakeFuzzConfFile creates a temporary file, then outputs WriteFuzzConf of j to it and returns the filepath.
// It is the caller's responsibility to delete the file.
func MakeFuzzConfFile(j job.Fuzzer) (string, error) {
	cf, err := ioutil.TempFile("", "act.*.conf")
	if err != nil {
		return "", fmt.Errorf("creating temporary fuzzer config file: %w", err)
	}

	werr := WriteFuzzConf(cf, j)
	cerr := cf.Close()

	return cf.Name(), errhelp.FirstError(werr, cerr)
}
