// Copyright (c) 2020 Matt Windsor and contributors
//
// This file is part of act-tester.
// Licenced under the MIT licence; see `LICENSE`.

package act

import (
	"io"
	"text/template"

	"github.com/MattWindsor91/act-tester/internal/model/job"
)

const fuzzConfTemplate = `# AUTOGENERATED BY TESTER
fuzz {
{{ if .Machine }}## MACHINE SPECIFIC OVERRIDES ##
  # Set to number of cores in machine to prevent thrashing.
  set param cap.threads to {{ .Machine.Cores }}
{{ end -}}
}
`

// WriteFuzzConf writes a fuzzer configuration based on j to w.
func WriteFuzzConf(w io.Writer, j job.Fuzzer) error {
	t, err := template.New("fuzzConf").Parse(fuzzConfTemplate)
	if err != nil {
		return err
	}
	return t.Execute(w, j)
}
