.nh
.TH act\-tester\-perturb 8

.SH NAME
.PP
act\-tester\-perturb \- perturbs a test plan


.SH SYNOPSIS
.PP
act\-tester\-perturb

.PP
.RS

.nf
[\-\-corpus\-size|\-n]=[value]
[\-\-seed|\-s]=[value]
[\-C]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
act\-tester\-perturb [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-corpus\-size, \-n\fP="": \fB\fCnumber\fR of corpus files to select for this test plan;
if positive, the planner will use all viable provided corpus files (default: 0)

.PP
\fB\-\-seed, \-s\fP="": \fB\fCseed\fR to use for any randomised components of this test plan; \-1 uses run time as seed (default: \-1)

.PP
\fB\-C\fP="": read tester config from this \fB\fCfile\fR
