// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	analysis "github.com/MattWindsor91/act-tester/internal/model/plan/analysis"
	mock "github.com/stretchr/testify/mock"

	observer "github.com/MattWindsor91/act-tester/internal/controller/analyse/observer"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnAnalysis provides a mock function with given fields: a
func (_m *Observer) OnAnalysis(a analysis.Analysis) {
	_m.Called(a)
}

// OnSave provides a mock function with given fields: s
func (_m *Observer) OnSave(s observer.Saving) {
	_m.Called(s)
}

// OnSaveFileMissing provides a mock function with given fields: s, missing
func (_m *Observer) OnSaveFileMissing(s observer.Saving, missing string) {
	_m.Called(s, missing)
}
