// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	analysis "github.com/MattWindsor91/act-tester/internal/plan/analysis"
	mock "github.com/stretchr/testify/mock"

	observer "github.com/MattWindsor91/act-tester/internal/controller/analyse/observer"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnAnalysis provides a mock function with given fields: a
func (_m *Observer) OnAnalysis(a analysis.Analysis) {
	_m.Called(a)
}

// OnArchive provides a mock function with given fields: s
func (_m *Observer) OnArchive(s observer.ArchiveMessage) {
	_m.Called(s)
}
