.nh
.TH c4t\-mkdoc 8

.SH NAME
.PP
c4t\-mkdoc \- makes documentation for c4t commands


.SH SYNOPSIS
.PP
c4t\-mkdoc

.PP
.RS

.nf
[\-\-help|\-h]
[\-d]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
c4t\-mkdoc [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-help, \-h\fP: show help

.PP
\fB\-d\fP="": \fB\fCdirectory\fR to which outputs will be written (default: docs)
