// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	id "github.com/MattWindsor91/act-tester/internal/model/id"
	compiler "github.com/MattWindsor91/act-tester/internal/stage/mach/compiler"

	mock "github.com/stretchr/testify/mock"

	subject "github.com/MattWindsor91/act-tester/internal/model/subject"
)

// SubjectPather is an autogenerated mock type for the SubjectPather type
type SubjectPather struct {
	mock.Mock
}

// Prepare provides a mock function with given fields: compilers
func (_m *SubjectPather) Prepare(compilers []id.ID) error {
	ret := _m.Called(compilers)

	var r0 error
	if rf, ok := ret.Get(0).(func([]id.ID) error); ok {
		r0 = rf(compilers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubjectPaths provides a mock function with given fields: sc
func (_m *SubjectPather) SubjectPaths(sc compiler.SubjectCompile) subject.CompileFileset {
	ret := _m.Called(sc)

	var r0 subject.CompileFileset
	if rf, ok := ret.Get(0).(func(compiler.SubjectCompile) subject.CompileFileset); ok {
		r0 = rf(sc)
	} else {
		r0 = ret.Get(0).(subject.CompileFileset)
	}

	return r0
}
