// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	compilation "github.com/MattWindsor91/act-tester/internal/subject/compilation"

	id "github.com/MattWindsor91/act-tester/internal/model/id"

	mock "github.com/stretchr/testify/mock"
)

// SubjectPather is an autogenerated mock type for the SubjectPather type
type SubjectPather struct {
	mock.Mock
}

// Prepare provides a mock function with given fields: compilers
func (_m *SubjectPather) Prepare(compilers []id.ID) error {
	ret := _m.Called(compilers)

	var r0 error
	if rf, ok := ret.Get(0).(func([]id.ID) error); ok {
		r0 = rf(compilers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubjectPaths provides a mock function with given fields: sc
func (_m *SubjectPather) SubjectPaths(sc compilation.Name) compilation.CompileFileset {
	ret := _m.Called(sc)

	var r0 compilation.CompileFileset
	if rf, ok := ret.Get(0).(func(compilation.Name) compilation.CompileFileset); ok {
		r0 = rf(sc)
	} else {
		r0 = ret.Get(0).(compilation.CompileFileset)
	}

	return r0
}
