// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	copier "github.com/MattWindsor91/act-tester/internal/copier"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnCopy provides a mock function with given fields: _a0
func (_m *Observer) OnCopy(_a0 copier.Message) {
	_m.Called(_a0)
}
