// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnCopy provides a mock function with given fields: dst, src
func (_m *Observer) OnCopy(dst string, src string) {
	_m.Called(dst, src)
}

// OnCopyFinish provides a mock function with given fields:
func (_m *Observer) OnCopyFinish() {
	_m.Called()
}

// OnCopyStart provides a mock function with given fields: nfiles
func (_m *Observer) OnCopyStart(nfiles int) {
	_m.Called(nfiles)
}
