.nh
.TH act\-tester\-mkdoc 8

.SH NAME
.PP
act\-tester\-mkdoc \- makes documentation for act\-tester commands


.SH SYNOPSIS
.PP
act\-tester\-mkdoc

.PP
.RS

.nf
[\-\-help|\-h]
[\-d]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
act\-tester\-mkdoc [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-\-help, \-h\fP: show help

.PP
\fB\-d\fP="": \fB\fCdirectory\fR to which outputs will be written (default: docs)
