// Code generated by "stringer -type=Status"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Ok-1]
	_ = x[Flagged-2]
	_ = x[CompileFail-3]
	_ = x[CompileTimeout-4]
	_ = x[RunFail-5]
	_ = x[RunTimeout-6]
}

const _Status_name = "UnknownOkFlaggedCompileFailCompileTimeoutRunFailRunTimeout"

var _Status_index = [...]uint8{0, 7, 9, 16, 27, 41, 48, 58}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
