// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	id "github.com/c4-project/c4t/internal/id"
	compiler "github.com/c4-project/c4t/internal/model/service/compiler"

	mock "github.com/stretchr/testify/mock"
)

// CompilerLister is an autogenerated mock type for the CompilerLister type
type CompilerLister struct {
	mock.Mock
}

// Compilers provides a mock function with given fields:
func (_m *CompilerLister) Compilers() (map[id.ID]compiler.Compiler, error) {
	ret := _m.Called()

	var r0 map[id.ID]compiler.Compiler
	if rf, ok := ret.Get(0).(func() map[id.ID]compiler.Compiler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[id.ID]compiler.Compiler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
