// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	machine "github.com/MattWindsor91/act-tester/internal/model/machine"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnMachines provides a mock function with given fields: m
func (_m *Observer) OnMachines(m machine.Message) {
	_m.Called(m)
}
