// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	compiler "github.com/MattWindsor91/c4t/internal/model/service/compiler"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnCompilerConfig provides a mock function with given fields: _a0
func (_m *Observer) OnCompilerConfig(_a0 compiler.Message) {
	_m.Called(_a0)
}
