// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	backend "github.com/c4-project/c4t/internal/model/service/backend"
	mock "github.com/stretchr/testify/mock"
)

// Resolver is an autogenerated mock type for the Resolver type
type Resolver struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: s
func (_m *Resolver) Resolve(s *backend.Spec) (backend.Backend, error) {
	ret := _m.Called(s)

	var r0 backend.Backend
	if rf, ok := ret.Get(0).(func(*backend.Spec) backend.Backend); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backend.Backend)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*backend.Spec) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
