// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	builder "github.com/MattWindsor91/act-tester/internal/subject/corpus/builder"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnBuild provides a mock function with given fields: _a0
func (_m *Observer) OnBuild(_a0 builder.Message) {
	_m.Called(_a0)
}
