// Package director contains the top-level ACT test director, which manages a full testing campaign.
package director

import (
	"context"

	"github.com/sirupsen/logrus"

	"github.com/MattWindsor91/act-tester/internal/pkg/model"
)

// Director contains the main state and configuration for the test director.
type Director struct {
	Plan model.Plan

	// OutDir contains the root output directory for things generated by this director.
	OutDir string
}

// DirectPlanFile loads the plan pointed to by file, then runs the director.
func (d *Director) DirectPlanFile(ctx context.Context, file string) error {
	if err := d.Plan.Load(file); err != nil {
		return err
	}
	logrus.Infof("Using plan from %v.", d.Plan.Creation)
	return d.Direct(ctx)
}

// Direct runs the director d over whichever test plan is loaded into it.
func (d *Director) Direct(ctx context.Context) error {
	var err error

	var ps *pathset
	if ps, err = d.prepare(); err != nil {
		return err
	}

	var fc []string
	if fc, err = d.fuzzCorpus(ps); err != nil {
		return err
	}

	return d.directMachines(ctx, ps, fc)
}

func (d *Director) prepare() (*pathset, error) {
	// TODO(@MattWindsor91)

	return nil, nil
}

func (d *Director) fuzzCorpus(_ *pathset) (corpusFiles []string, err error) {
	// TODO(@MattWindsor91)

	return nil, nil
}

func (d *Director) directMachines(ctx context.Context, ps *pathset, fc []string) error {
	return d.Plan.ParMachines(ctx, func(ectx context.Context, m model.MachinePlan) error {
		return d.directMachine(ectx, ps, fc, m)
	})
}

func (d *Director) directMachine(_ context.Context, _ *pathset, _ []string, _ model.MachinePlan) error {
	// TODO(@MattWindsor91)
	return nil
}
