// Package director contains the top-level ACT test director, which manages a full testing campaign.
package director

import (
	"context"

	"github.com/MattWindsor91/act-tester/internal/pkg/model"
	"github.com/sirupsen/logrus"
	"golang.org/x/sync/errgroup"
)

// Director contains the main state and configuration for the test director.
type Director struct {
	model.PlanLoader

	// OutDir contains the root output directory for things generated by this director.
	OutDir string
}

// Direct runs the director d over whichever test plan is loaded into it.
// If no plan is loaded, it tries to load one from the given file.
func (d *Director) Direct(ctx context.Context) error {
	var err error

	if err = d.loadPlanIfNeeded(); err != nil {
		return err
	}
	logrus.Infof("Using plan from %v.", d.Plan.Creation)

	var ps *Pathset
	if ps, err = d.prepare(); err != nil {
		return err
	}

	var fc []string
	if fc, err = d.fuzzCorpus(ps); err != nil {
		return err
	}

	return d.directMachines(ctx, ps, fc)
}

func (d *Director) loadPlanIfNeeded() error {
	if d.Plan == nil {
		return d.LoadPlan()
	}

	return nil
}

func (d *Director) prepare() (*Pathset, error) {
	// TODO(@MattWindsor91)

	return nil, nil
}

type Pathset struct {
	FuzzDir string
}

func (d *Director) fuzzCorpus(_ *Pathset) (corpusFiles []string, err error) {
	// TODO(@MattWindsor91)

	return nil, nil
}

func (d *Director) directMachines(ctx context.Context, ps *Pathset, fc []string) error {
	eg, ectx := errgroup.WithContext(ctx)
	for _, m := range d.Plan.Machines {
		eg.Go(func() error { return d.directMachine(ectx, ps, fc, m) })
	}

	return nil
}

func (d *Director) directMachine(_ context.Context, _ *Pathset, _ []string, _ model.MachinePlan) error {
	// TODO(@MattWindsor91)
	return nil
}
