// Copyright (c) 2020 Matt Windsor and contributors
//
// This file is part of act-tester.
// Licenced under the MIT licence; see `LICENSE`.

// Package director contains the top-level ACT test director, which manages a full testing campaign.
package director

import (
	"context"
	"errors"

	"github.com/MattWindsor91/act-tester/internal/pkg/config"
)

// Director contains the main state and configuration for the test director.
type Director struct {
	// config is the top-level configuration for the tester.
	config *config.Config

	// outDir contains the root output directory for things generated by this director.
	outDir string
}

var (
	// ErrConfigNil occurs when we try to build a Director without a config.
	ErrConfigNil = errors.New("config nil")
	// ErrNoOutDir occurs when we try to build a Director with no output directory specified in the config.
	ErrNoOutDir = errors.New("no output directory specified in config")
)

// New creates a new Director given a global act-tester config.
// It fails if the config is missing or ill-formed.
func New(c *config.Config) (*Director, error) {
	if c == nil {
		return nil, ErrConfigNil
	}
	if c.Backend == nil {
		return nil, errors.New("config has no backend")
	}
	if c.OutDir == "" {
		return nil, ErrNoOutDir
	}

	return &Director{config: c, outDir: c.OutDir}, nil
}

// Direct runs the director d over whichever test plan is loaded into it.
func (d *Director) Direct(ctx context.Context) error {
	var err error

	var ps *pathset
	if ps, err = d.prepare(); err != nil {
		return err
	}

	var fc []string
	if fc, err = d.fuzzCorpus(ps); err != nil {
		return err
	}

	return d.directMachine(ctx, ps, fc)
}

func (d *Director) prepare() (*pathset, error) {
	// TODO(@MattWindsor91)

	return nil, nil
}

func (d *Director) fuzzCorpus(_ *pathset) (corpusFiles []string, err error) {
	// TODO(@MattWindsor91)

	return nil, nil
}

func (d *Director) directMachine(_ context.Context, _ *pathset, _ []string) error {
	// TODO(@MattWindsor91)
	return nil
}
