// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CopyObserver is an autogenerated mock type for the CopyObserver type
type CopyObserver struct {
	mock.Mock
}

// OnCopy provides a mock function with given fields: dst, src
func (_m *CopyObserver) OnCopy(dst string, src string) {
	_m.Called(dst, src)
}

// OnCopyFinish provides a mock function with given fields:
func (_m *CopyObserver) OnCopyFinish() {
	_m.Called()
}

// OnCopyStart provides a mock function with given fields: nfiles
func (_m *CopyObserver) OnCopyStart(nfiles int) {
	_m.Called(nfiles)
}
