// Code generated by "stringer -type=Status"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Ok-1]
	_ = x[Filtered-2]
	_ = x[Flagged-3]
	_ = x[CompileFail-4]
	_ = x[CompileTimeout-5]
	_ = x[RunFail-6]
	_ = x[RunTimeout-7]
}

const _Status_name = "UnknownOkFilteredFlaggedCompileFailCompileTimeoutRunFailRunTimeout"

var _Status_index = [...]uint8{0, 7, 9, 17, 24, 35, 49, 56, 66}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
