// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	compiler "github.com/MattWindsor91/act-tester/internal/model/service/compiler"
	mock "github.com/stretchr/testify/mock"
)

// CompilerObserver is an autogenerated mock type for the CompilerObserver type
type CompilerObserver struct {
	mock.Mock
}

// OnCompilerPlan provides a mock function with given fields: c
func (_m *CompilerObserver) OnCompilerPlan(c compiler.Named) {
	_m.Called(c)
}

// OnCompilerPlanFinish provides a mock function with given fields:
func (_m *CompilerObserver) OnCompilerPlanFinish() {
	_m.Called()
}

// OnCompilerPlanStart provides a mock function with given fields: ncompilers
func (_m *CompilerObserver) OnCompilerPlanStart(ncompilers int) {
	_m.Called(ncompilers)
}
