.nh
.TH act\-tester\-lift 8

.SH NAME
.PP
act\-tester\-lift \- runs the harness\-lifter phase of an ACT test


.SH SYNOPSIS
.PP
act\-tester\-lift

.PP
.RS

.nf
[\-A]=[value]
[\-d]=[value]
[\-x]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
act\-tester\-lift [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB\-A\fP="": read ACT config from this \fB\fCfile\fR

.PP
\fB\-d\fP="": \fB\fCdirectory\fR to which outputs will be written (default: lift\_results)

.PP
\fB\-x\fP: if true, use 'dune exec' to run OCaml ACT binaries
